CREATE TABLE `products` (
  `id` int NOT NULL AUTO_INCREMENT,
  `name` varchar(255) NOT NULL,
  `price` decimal(10,2) NOT NULL,
  `description` text,
  `category` varchar(50) DEFAULT 'NULL',
  `image_urls` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `rating` decimal(2,1) DEFAULT NULL,
  `review_count` int DEFAULT '0',
  `highlights` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `specifications` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `whats_in_box` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  `stock_quantity` int DEFAULT '0',
  `created_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` timestamp NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  `is_deleted` tinyint(1) NOT NULL DEFAULT '0',
  `deleted_at` datetime DEFAULT NULL,
  `total_sold` int DEFAULT '0',
  `sub_categories` text,
  `tags` text,
  `is_variable_product` tinyint(1) NOT NULL DEFAULT '0',
  `product_code` varchar(64) DEFAULT NULL,
  `discount_price` decimal(12,2) DEFAULT NULL,
  `stock_status` varchar(32) DEFAULT NULL,
  `videos` longtext CHARACTER SET utf8mb4 COLLATE utf8mb4_bin,
  PRIMARY KEY (`id`),
  KEY `ix_products_category` (`category`),
  KEY `idx_products_is_deleted` (`is_deleted`),
  KEY `idx_products_is_deleted_category` (`is_deleted`,`category`),
  KEY `idx_products_is_deleted_created_at` (`is_deleted`,`created_at`),
  KEY `idx_products_category` (`category`),
  KEY `idx_products_created_at` (`created_at`),
  CONSTRAINT `fk_products_category` FOREIGN KEY (`category`) REFERENCES `categories` (`id`) ON DELETE SET NULL ON UPDATE CASCADE
) ENGINE=InnoDB AUTO_INCREMENT=911 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci;
